#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyusb
Version  : 1.1.0
Release  : 8
URL      : https://files.pythonhosted.org/packages/12/9b/8f5be839753667c39fe522162bea7f8121f28ba49c5ad1e5681681967c79/pyusb-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/12/9b/8f5be839753667c39fe522162bea7f8121f28ba49c5ad1e5681681967c79/pyusb-1.1.0.tar.gz
Summary  : Python USB access module
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyusb-license = %{version}-%{release}
Requires: pyusb-python = %{version}-%{release}
Requires: pyusb-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv

%description
PyUSB offers easy USB devices communication in Python.
        It should work without additional code in any environment with
        Python >= 2.4, ctypes and a pre-built USB backend library

%package license
Summary: license components for the pyusb package.
Group: Default

%description license
license components for the pyusb package.


%package python
Summary: python components for the pyusb package.
Group: Default
Requires: pyusb-python3 = %{version}-%{release}

%description python
python components for the pyusb package.


%package python3
Summary: python3 components for the pyusb package.
Group: Default
Requires: python3-core
Provides: pypi(pyusb)

%description python3
python3 components for the pyusb package.


%prep
%setup -q -n pyusb-1.1.0
cd %{_builddir}/pyusb-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600182820
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyusb
cp %{_builddir}/pyusb-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/pyusb/a2d04db8cd93d1be66a62f2ba50283b8ac9d5653
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyusb/a2d04db8cd93d1be66a62f2ba50283b8ac9d5653

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
